server:
  port: 9528

spring:
  application:
    name: app-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server1.com:8001/eureka/,http://eureka-server2.com:8002/eureka/,http://eureka-server3.com:8003/eureka/
  instance:
      instance-id: ${spring.application.name}:${server.port} #自定义服务名称信息
      prefer-ip-address: true #访问路径可以显示服务器真实的ip

management:
  metrics:
    web:
      server:
        auto-time-requests: false


