server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server1.com:8001/eureka/,http://eureka-server2.com:8002/eureka/,http://eureka-server3.com:8003/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: app-product
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
